version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./videoserver.conf:/etc/nginx/conf.d/default.conf
      - ./web:/app/web
    depends_on:
      - ion-sfu

  ion-sfu:
    image: pionwebrtc/ion-sfu:v1.10.6-jsonrpc
    container_name: ion-sfu
    restart: unless-stopped
    ports:
      - 7000:7000
      - 5000-5020:5000-5020/udp
